			<!-- TODO: rimuovere e integrare in altri .js di nostra mano
   			================================================== -->
    		<script  type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    		<script  type="text/javascript" src="js/bootstrap.min.js"></script>

			<!-- ================================================== -->
						
			<script type="text/javascript" src="js/stringLib.js"></script>
			<script type="text/javascript" src="js/netLib.js"></script>
			
			<script type="text/javascript" src="js/login.js"></script>