			<!-- TODO: rimuovere e integrare in altri .js di nostra mano
   			================================================== -->
    		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    		<script src="js/bootstrap.min.js"></script>
			
			<!-- ================================================== -->
						
			<script src="js/stringLib.js"></script>
			<script src="js/netLib.js"></script>
			<script src="js/login.js"></script>